services:
  - type: web
    name: behavioral-biometrics-app
    env: python
    buildCommand: pip install -r behavioral-biometrics/requirements.txt
    startCommand: python behavioral-biometrics/app.py
    pythonVersion: 3.10.13
    plan: free
    autoDeploy: true
