services:
  - type: web
    name: behavioral-biometrics
    env: python
    plan: free
    rootDir: behavioral-biometrics
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.13
